site_name: Cheshire Cat Docs
repo_url: https://github.com/pieroit/cheshire-cat

docs_dir: mkdocs
site_dir: docs

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_autoplay: False
      video_type: mp4
  - search

nav:
  - Hello, dear: index.md
  - Conceptual:
      - The Cheshire Cat:
          - The Mad Hatter: conceptual/cheshire_cat/mad_hatter.md
          - The Rabbit Hole: conceptual/cheshire_cat/rabbit_hole.md
          - The Agent: conceptual/cheshire_cat/agent.md
      - Language Models: conceptual/language_models/llm.md
#          - Large Language Model: conceptual/language_models/llm.md
      - Memory:
          - Vector Memory: conceptual/memory/vector_memory.md
          - Long Term Memory: conceptual/memory/long_term_memory.md
          - Working Memory: conceptual/memory/working_memory.md
      - Prompts:
          - HyDE prompt: conceptual/prompts/hyde.md
          - Main Prompt: conceptual/prompts/main_prompt.md
          - Summarization Prompt: conceptual/prompts/summarization.md
      - Plugins: conceptual/plugins.md
#          - Hooks: conceptual/plugins/hooks.md
#          - Tools: conceptual/plugins/tools.md
  - Technical:
      - Getting Started: technical/getting-started.md
      - How the Cat works: technical/how-the-cat-works.md
      - Basics:
          - Folders & APIs: technical/basics/basics.md
          - The Cat Core: technical/basics/cat-core.md
          - Admin Interface: technical/basics/admin-interface.md
      - Plugins:
          - How to write a plugin: technical/plugins/plugins.md
          - Tools: technical/plugins/tools.md
          - Hooks: technical/plugins/hooks.md
      - Advanced: technical/advanced.md
      - Tutorials:
          - Overview: technical/tutorials/overview.md
          - Installation: technical/tutorials/installation.md
  - FAQ: faq.md

theme:
  name: material
  favicon: assets/img/favicon.ico
  logo: assets/img/cheshire-cat-logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    #text: Old Standard TT
    text: Ubuntu
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pieroit/cheshire-cat
      name: The Cheshire Cat repo on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bHX5sNFCYU
      name: The Cheshire Cat Discord Server

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
