site_name: Cheshire Cat Docs
repo_url: https://github.com/pieroit/cheshire-cat

theme:
  name: material
  favicon: assets/img/favicon.ico
  logo: assets/img/cheshire-cat-logo.svg
  palette:
    primary: grey
  font:
    text: Old Standard TT
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pieroit/cheshire-cat
      name: The Cheshire Cat repo on GitHub
