site_name: Cheshire Cat Docs
repo_url: https://github.com/pieroit/cheshire-cat

docs_dir: mkdocs
site_dir: docs

plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_autoplay: False
      video_type: mp4
  - search

nav:
  - Hello, dear: index.md
  - Concepts: conceptual/conceptual.md
  - API: API/api.md
  - Getting Started: getting-started.md
  - How the Cat works: how-the-cat-works.md
  - Basics:
      - Folders & APIs: basics/basics.md
      - The Cat Core: basics/cat-core.md
      - Admin Interface: basics/admin-interface.md
  - Plugins:
      - How to write a plugin: plugins/plugins.md
      - Tools: plugins/tools.md
      - Hooks: plugins/hooks.md
  - Advanced: advanced.md
  - Tutorials:
      - Overview: tutorials/overview.md
      - Installation: tutorials/installation.md
  - FAQ: faq.md
  - TO DELETE: features.md

theme:
  name: material
  favicon: assets/img/favicon.ico
  logo: assets/img/cheshire-cat-logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    #text: Old Standard TT
    text: Ubuntu
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pieroit/cheshire-cat
      name: The Cheshire Cat repo on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/bHX5sNFCYU
      name: The Cheshire Cat Discord Server

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
